### ISSUE TITLE
3D Grid Scans: Create 2nd Nexus File

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#100]
For 3D grid scans to work a second nexus file needs to be created. This was done in https://github.com/DiamondLightSource/python-artemis/tree/testing_round_5 but needs tidying up

## Notes
* The second file should have the same template for the filename but with the run number incremented
* Artemis should still be able to do 2D grid scans

**Comment by DominicOram** [comment]
Note that because GDA is unaware of the 2nd file it is actually overwriting it

**Comment by bentom08** [comment]
Leaving a reminder here to make sure the 2 nexus files are written with different omega start/end values.

**Comment by DominicOram** [comment]
Requires https://github.com/dials/nexgen/issues/53
