### ISSUE TITLE
i03 testing: round 6

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#111]
Mainly to test:
* New user for https://github.com/DiamondLightSource/python-artemis/issues/84
* https://github.com/DiamondLightSource/python-artemis/issues/49

**Comment by DominicOram** [comment]
Testing went as follows:
- [ ] https://github.com/DiamondLightSource/python-artemis/issues/84 was successful with new credentials. However, position is incorrect https://github.com/DiamondLightSource/python-artemis/issues/113
- [ ] It's more stable to search on dc group id in zocalo
- [ ] https://github.com/DiamondLightSource/python-artemis/pull/106 didn't work
- [ ] We're currently moving to the leftmost of the box, should probably move to its centre
- [ ] We're putting omega into ISpyB as -90, it should be +90
- [ ] Before doing the final smargon move we needed to wait for omega to get back to 0
- [ ] The results being returned from analysis do not look correct e.g. for https://ispyb.diamond.ac.uk/dc/visit/cm31105-2/dcg/7451582 we got `[6, 4, 3]` but (by eye) it looks more like `[4, 8, 5]`. @rjgildea let us know when you have something you want to try with this

**Comment by DominicOram** [comment]
Branches used were:
* https://github.com/DiamondLightSource/python-artemis/tree/i03_testing_round_6_26_05
* https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/35058/10

**Comment by bentom08** [comment]
Do we know we moved to the leftmost edge of the box rather than the centre or are we just assuming? Because the start position we get from GDA and use to calculate the position of the centring results box is the firstd box's centre, not its edge, so I wouldn't have thought we'd need to add anything to it.

**Comment by DominicOram** [comment]
Yep, I agree, will remove that point.
