### ISSUE TITLE
Position in syncweb is being calculated wrong

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#113]
In e.g. https://ispyb.diamond.ac.uk/dc/visit/cm31105-2/dcg/7450520 image 1 and image 40 should have the same x value. They currently have it set at -19 and +361

**Comment by bentom08** [comment]
Probably something to do with the "snaked" ispyb field in each scan. Synchweb position coords seem to be assuming a non-snaked scan.

**Comment by bentom08** [comment]
On further investigation this appears to be an issue with all grid scans in synchweb. Probably needs to be brought up with the synchweb devs to resolve.

**Comment by bentom08** [comment]
Jira ticket raised with scisoft https://jira.diamond.ac.uk/browse/SCI-14169

**Comment by DominicOram** [comment]
Given this is a synchweb issue I'm going to close it on our side
