### ISSUE TITLE
Snaphots: Ophyd device for OAV

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#124]
As part of https://github.com/DiamondLightSource/python-artemis/issues/91 we need an ophyd device for the OAV.

## Acceptance Criteria
* There is an ophyd device for the OAV
* There is enough functionality to take snapshots with the OAV
* There are unit tests against this (if appropriate)

**Comment by DominicOram** [comment]
@npat113 feel free to update this with progress and links to what you've done.

**Comment by npat113** [comment]
uploaded an initial device based on cambase and tried to match up the plugins. Some are missing and will need created, all need tested.

**Comment by DominicOram** [comment]
Thanks @npat113, which branch is that on?

**Comment by npat113** [comment]
124_Snapshots_ophyd_device_for_oav

**Comment by DominicOram** [comment]
Looking in the GDA code to take a snapshot all it actually does is take a still from the stream at `http://bl03i-di-serv-01.diamond.ac.uk:8080/OAV.mjpg.mjpg` and saves that to file. So generally doesn't need to interact with the hardware (assuming it is already configured correctly).

**Comment by npat113** [comment]
True, but moving on from this is pin tip centring and that is a bit more demanding. You didn't think I'd be happy just with stills did you ;)
