### ISSUE TITLE
Undulator gap: Get using ophyd

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#125]
Currently the undulator gap is passed from GDA to Artemis. There is no reason that Artemis could not read the undulator gap itself, this would be good as it will make Artemis more standalone and less dependent on GDA.

## Acceptance Criteria
* There is an Ophyd device for the undulator
* Artemis reads the gap from this device and GDA no longer sends it

**Comment by DominicOram** [comment]
The PV for the undulator gap is `${gda.idgap.pv.prefix}-MO-SERVC-01:BLGAPMTR` where `${gda.idgap.pv.prefix}` is beamline specific. On i03 it is `SR03I`.

**Comment by npat113** [comment]
the epics undulator gap interface is rather odd (and irritating). Currently there is a set PV and an execute PV. This might be a gui feature, but if you're seeing odd behaviour then it may be related.
