### ISSUE TITLE
Synchrotron Mode: Get using Ophyd

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#126]
Currently the synchrotron mode is passed from GDA to Artemis. There is no reason that Artemis could not read the synchrotron mode itself, this would be good as it will make Artemis more standalone and less dependent on GDA.

## Acceptance Criteria
* There is an Ophyd device for the synchrotron mode
* Artemis reads the synchrotron mode from this device and GDA no longer sends it

**Comment by DominicOram** [comment]
The PV for the synchrotron mode is CS-CS-MSTAT-01:MODE

**Comment by abbiemery** [comment]
Does this need to be a device? If it's just the reading of a pv is there another device which always needs it that a `synchroton_mode` signal could belong to?

**Comment by ndg63276** [comment]
There should probably be a device for the synchrotron, with this and other PVs, eg current, time till topup, time till topup ends, time till beam dump.

**Comment by abbiemery** [comment]
Okay good stuff. 

Additionally, just trying to figure out where these pvs are coming from, it's all a bit new to me. Is there a specific IOC for these synchrotron ones or is this something else entirely?

**Comment by ndg63276** [comment]
Not sure if there is a specific IOC, but really just a collection of PVs that are not specific to a beamline.
| Name | PV |
| ------ | ---- |
| Synchrotron Mode | CS-CS-MSTAT-01:MODE |
| Ring Energy | CS-CS-MSTAT-01:BEAMENERGY |
| Ring Current | SR-DI-DCCT-01:SIGNAL |
| Beam dump countdown | CS-CS-MSTAT-01:USERCOUNTDN |
| Topup start countdown | SR-CS-FILL-01:COUNTDOWN |
| Topup end countdown | SR-CS-FILL-01:ENDCOUNTDN |

**Comment by abbiemery** [comment]
I dug about and found the `CS-CS-MSTAT-01:MODE` PV in the machine IOC `CS-CS-IOC-02` from the machineStatus support module, just putting the pieces together.

Thank you for the link, I'll take a look!

**Comment by DominicOram** [comment]
We will need most of these PVs at some point so might as well get them into the Device, not sure it matters too much if they're in one IOC in the backend or not. We should group them in ophyd under what's logical from the perspective of the beamline.
