### ISSUE TITLE
Snapshots: Overlay grid on the OAV

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#128]
After a snapshot image is taken in GDA the gridscan grid is overlayed on top of the picture. We should do this in Artemis. We can use how GDA does it as a guide but we can also look at leveraging other Python 3 libraries if they're helpful.

**Comment by ndg63276** [comment]
We would like to produce 3 snapshots, one with no grid, one with the grid outline, and one with the full grid. At the moment GDA passes in the same image 3 times for some reason. Passing 3 snapshots into ISPyB gives the end user the choice what to see. (See https://jira.diamond.ac.uk/browse/I03-700)

**Comment by DominicOram** [comment]
Thanks @ndg63276, this also answers https://github.com/DiamondLightSource/python-artemis/issues/44
