### ISSUE TITLE
Publish metrics about time taken for each step in a plan

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#129]
As a scientist it will be very useful to see visually when specific operations are taking place so that we can easily speed up operations. Note that some operations are going to happen at the same time and so a gantt chant kind of view will probably be helpful. We should make sure to use standard tools used e.g. Prometheus/Grafana probably.

**Comment by DominicOram** [comment]
I wanted to get this idea written down somewhere as it feels like something would be useful when we get to wanting to find new ways of reducing down time but it's likely out of scope for Artemis and probably represents a separate service. @callumforrester, @graeme-winter and @ndg63276 I welcome any thoughts on usefulness, scope etc.

**Comment by rjgildea** [comment]
@DominicOram this is precisely what I envisioned in [this graduate project proposal](https://confluence.diamond.ac.uk/display/SSCC/Graduate+project+idea%3A+Distributed+tracing+for+data+analysis+workflows) - whilst the project itself is focussed on Zocalo, there is absolutely no reason it couldn't be extended more widely to encompass the entire data acquisition/analysis process (and this would increase its usefulness).

**Comment by DominicOram** [comment]
Thanks @rjgildea, that looks perfect. We should definitely do it together in a common way. I think it's unlikely we'll be doing this anytime soon so let us know if any progress is made from your side. I'd be happy to help supervise a graduate if useful.

**Comment by callumforrester** [comment]
Will start a thread in the NSLS-II slack channel, see if they have any input

**Comment by DominicOram** [comment]
This is a good start but we probably want to hook it into something like prometheus and timestamp other events such as nexus writing

**Comment by DominicOram** [comment]
Dan Fernandes has been working on this for analysis, makes sense to use the same infrastructure.

For this to be done proof of principle in memory is
