### ISSUE TITLE
Fix FGS system tests

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#13]
Following the work done in https://gitlab.diamond.ac.uk/controls/python3/s03_utils/-/merge_requests/4 S03 is now reporting that twice the number of images than expected are being taken.

# Acceptance Criteria
* The code in the FGS system test that forces the expected images to be twice the expected is removed
* System tests still work

**Comment by DominicOram** [comment]
System tests inside gridscan may need updating to use latest versions of classes

**Comment by abbiemery** [comment]
The Zebra and eiger system tests need updating and fixing too. The others pass when run with s03 working.

**Comment by dperl-dls** [comment]
this is described in more detail by other open issues
