### ISSUE TITLE
Robot load testing 14/06

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#1446]
* `RobotLoadThenCentre` has `snapshot_directory` as required but it's not if you specify `storage_directory` - see https://github.com/DiamondLightSource/mx-bluesky/issues/235
* `sanpshot_omegas_deg`: - see https://github.com/DiamondLightSource/mx-bluesky/issues/235
    * Why is it required for robot load, it's not used in the plan?
    * It should have a sensible default 
    * What does it being optional mean in this context? Why not just use `[]`?
* `RobotLoadIspybCallback` is not started in the callback process - https://github.com/DiamondLightSource/hyperion/pull/1451
* No `OK` on the `SUCCESS` in synchweb - https://github.com/DiamondLightSource/hyperion/pull/1451
* Images not rendering properly in synchweb 
![image](https://github.com/DiamondLightSource/hyperion/assets/10086797/03a24a23-a7e0-4b20-8f14-5093a48924ca). Need to additionally create a thumbnail with the same name but `t` on the end (e.g. `165220_oav_snapshot_after_load.png` and `165220_oav_snapshot_after_loadt.png`) where the thumbnail is scaled down to be 192 pixels high - https://github.com/DiamondLightSource/dodal/issues/628
* We're occasionally getting 700 - sample position write failure errors on the robot. Waiting on the readback for next pin to match the setpoint (https://github.com/bluesky/ophyd-async/issues/386) seemed to maybe fix this... - https://github.com/DiamondLightSource/hyperion/pull/1451
* Images are the other way round in synchweb - https://github.com/DiamondLightSource/hyperion/pull/1451
* OAV image was taken too early and so gripper in the way. Waiting for smargon moved then taking image fixed this - https://github.com/DiamondLightSource/hyperion/pull/1451
* Error of "5640 Cannot execute during RUN" -  @ndg63276 any ideas why this might happen? - Discussed, due to unrelated previous error
* If there is no pin we just get a timeout and no clean error on synchweb - https://github.com/DiamondLightSource/hyperion/pull/1451
* On timeout due to robot error we should put the error message in ispyb - https://github.com/DiamondLightSource/hyperion/pull/1451

**Comment by DominicOram** [comment]
Images not rendering properly in synchweb and no `OK` on the `SUCCESS`.
![image](https://github.com/DiamondLightSource/hyperion/assets/10086797/03a24a23-a7e0-4b20-8f14-5093a48924ca)

**Comment by DominicOram** [comment]
Need to additionally create a thumbnail with the same name but `t` on the end (e.g. `165220_oav_snapshot_after_load.png` and `165220_oav_snapshot_after_loadt.png) where the thumbnail is scaled down to be 192 pixels high

**Comment by DominicOram** [comment]
We're occasionally getting 700 - sample position write failure errors on the robot. Waiting on the readback for next pin to match the setpoint (https://github.com/bluesky/ophyd-async/issues/386) seemed to maybe fix this...

**Comment by ndg63276** [comment]
Discussed in person but to document, error 5640 means some sort of syntax error, "Cannot execute during run" probably means something else was running or erroring when you tried to send a command.

In general though, command errors can be ignored, only program and control errors need to be looked at.
