### ISSUE TITLE
Simulation: Write tickit simulations for Undulator Gap

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#146]
For us to be able to run system tests properly against S03 we will need a simple IOC that gives us the Undulator Gap

We can do this using the real `db` file and then the `EpicsAdapter` in `tickit`. See https://github.com/dls-controls/tickit/tree/master/tickit/devices/femto

**Comment by abbiemery** [comment]
@MattPrit

**Comment by DominicOram** [comment]
https://github.com/dls-controls/tickit/issues/64
