### ISSUE TITLE
Deployment and start up script for Artemis

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#163]
As a developer it's frustrating to have to remember how to deploy Artemis every time I go down to the beamline. We should:
* Tag a `0.1` release
* Document how to tag a release 
* Have a script that:
    * Pulls a specified version (or the latest if none specified)
    * Starts Artemis, making sure to:
         * module unload controls_dev
         * pipenv install
         * module load dials
         * set ispyb config

**Comment by bentom08** [comment]
ssh ixx-control, sudo su - gda2, module load python/3.10? Also the pipenv needs to specify the python version i.e. pipenv install --python 3.10. 

Also if we're going to put the ispyb config file path in the repo anyway, would a better solution not be to just put the file path in artemis?

**Comment by DominicOram** [comment]
Thanks. Re ISpyB config, I want to make sure we're really careful not to accidentally use it in dev

**Comment by DominicOram** [comment]
As discussed, in dev it should point to an ISpyB dev environment that it's ok for us to write into

**Comment by bentom08** [comment]
core-config/gda_servers_core - the part of gdaservers script that does the sshing into gda2@ixx-control is in here
