### ISSUE TITLE
Move to using setup.cfg

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#181]
We should move the build system to using setup.cfg and subsequently sort out all the imports so they don't need the `src`

**Comment by abbiemery** [comment]
I've done this for now and moved the build and setup into ```setup.cfg```, however in the future we might need to change it again to instead use the ```pyproject.toml``` as raised by [pep 621](https://peps.python.org/pep-0621/) and defined [here](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/). Support for this in setuptools was introduced in 61.0.0 but not everything is quite on board yet. As such I did it the old way for convenience.
