### ISSUE TITLE
Switch from using max_voxel to centre_of_mass

### ISSUE THREAD

**Issue by bentom08** [DiamondLightSource/python-artemis#188]
In testing on the beamline it seems that the "max_voxel" coordinate returned from analysis was too heavily influenced by rogue spots of high diffraction.

The "centre_of_mass" coordinate provided by them should give more consistent results

**Comment by DominicOram** [comment]
Additionally the order of the data returned from Zocalo is reversed from the expected. i.e. it arrives as (z, y, x). We should account for this.
