### ISSUE TITLE
Box size is wrong in image meta data

### ISSUE THREAD

**Issue by ndg63276** [DiamondLightSource/python-artemis#191]
Do an artemis scan with boxes 20x20 microns, eg https://ispyb.diamond.ac.uk/dc/visit/cm31105-3/dcg/7690799
Query the sam_x position for each image:
```
h5ls -rd /dls/i03/data/2022/cm31105-3/xraycentring/manual/xrc_307_master.h5/entry/sample/transformations/sam_x
entry/sample/transformations/sam_x Dataset {494}
    Data:
        (0) 0.1589757, 0.1797757, 0.2005757, 0.2213757, 0.2421757, 0.2629757, 0.2837757, 0.3045757, 0.3253757, 0.3461757, 0.3669757, 0.3877757, 0.4085757, 0.4293757, 0.4501757, 0.4709757, 0.4917757, 0.5125757, 0.5333757,
        (19) 0.5541757, 0.5749757, 0.5957757, 0.6165757, 0.6373757, 0.6581757, 0.6789757, 0.6789757, 0.6581757, 0.6373757, 0.6165757, 0.5957757, 0.5749757, 0.5541757, 0.5333757, 0.5125757, 0.4917757, 0.4709757, 0.4501757,
...
```
These values are not 20 microns apart?

**Comment by bentom08** [comment]
I think this is an issue with Nexgen - https://github.com/dials/nexgen/issues/55

Only 25 sam_x positions are recorded for this scan despite it having 26 positions, so the box size is wrong: its calculated as (x_end - x_start)/25 instead of (x_end - x_start)/26

**Comment by ndg63276** [comment]
You're probably right, but to be clear, there are 26 sam_x positions recorded:
```
1 | 0.1589757
2 | 0.1797757
3 | 0.2005757
4 | 0.2213757
5 | 0.2421757
6 | 0.2629757
7 | 0.2837757
8 | 0.3045757
9 | 0.3253757
10 | 0.3461757
11 | 0.3669757
12 | 0.3877757
13 | 0.4085757
14 | 0.4293757
15 | 0.4501757
16 | 0.4709757
17 | 0.4917757
18 | 0.5125757
19 | 0.5333757
20 | 0.5541757
21 | 0.5749757
22 | 0.5957757
23 | 0.6165757
24 | 0.6373757
25 | 0.6581757
26 | 0.6789757
```

**Comment by bentom08** [comment]
Ah, my mistake, I miscounted. In that case it looks more like we may be passing the wrong end position. The first and last values are 520 microns apart, I think they should be 500 for this scan. The start/end positions are 148/648 on ispyb. I know we should be half a box out anyway because of the version on the beamline, but the end position is an extra 20 microns out.
