### ISSUE TITLE
Can't install databroker

### ISSUE THREAD

**Issue by MattPrit** [DiamondLightSource/python-artemis#220]
To access data outside the run engine `databroker` is required. To install `databroker` in the artemis pipenv, `pandas` is also required (else `from databroker import Broker` results in `ModuleNotFoundError: No module named 'pandas'`); installing pandas fails with 
```
ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
```

**Comment by evalott100** [comment]
I didn't reproduce the above error, however I managed to get Databroker working...

**Comment by DominicOram** [comment]
Closing as not worth doing for now
