### ISSUE TITLE
GDA should tell Artemis before it does snapshots

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#242]
There are probably some things we can do in Artemis before we know the exact grid co-ords (e.g. set up the detector). To speed things up GDA could tell Artemis that it's about to do a 3D grid scan and give it any meta data it requires before we know the gridscan.

## Acceptance Criteria
* There are two endpoints for fast grid scan, one to prep for the scan and one to perform it
* GDA correctly calls each
* As much logic as possible is done in the prep stage

**Comment by bentom08** [comment]
This will involve a lot of work to split different set up methods up into different sections. Detector/FGS/ispyb/nexus writing all use information from image recognition (number of images, coordinates), so all of them would need to be split into what can/can't be done without this information.
