### ISSUE TITLE
Log how long analysis took

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#245]
We should log how long analysis took and send it back to GDA as it needs to know for use in the next data collection.

# Acceptance Criteria
* The time analysis took was logged
* This is sent back to GDA and successfully put in the comment for the following data collection

**Comment by dperl-dls** [comment]
What is meant by "analysis" ?

**Comment by DominicOram** [comment]
Hmm... good question. I think the time between us calling `bps.kickoff(fgs_motors)`, which is when we actually trigger the data collection, and when we get something back from`zocalo_interaction.wait_for_result`. This is a bit annoying from a code perspective as it kind of muddles a lot of these timings in with the logic of the plan. I think that really needs looking at in https://github.com/DiamondLightSource/python-artemis/issues/164 though

**Comment by rjgildea** [comment]
I guess it would be the time between when you trigger the `RunAtEndOfCollect` script and when you receive a result from Zocalo (since we are currently triggering analysis at the end, rather than start, of data collection)?

**Comment by DominicOram** [comment]
Note that https://github.com/DiamondLightSource/python-artemis/pull/295 now logs this but we need to do part 2 of this issue still so reopening this

**Comment by DominicOram** [comment]
This is put in the ISPyB comments for the data collection

**Comment by DominicOram** [comment]
Look at whether we can do the x, y, z at the same time

**Comment by DominicOram** [comment]
We should put this in the comment for the grid scan, not the subsequent data collection
