### ISSUE TITLE
Clean up and give better error on SCAN_INVALID

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#248]
If the gridscan params would cause the smargon to go out of it's limits then the `SCAN_INVALID` PV goes low and the fgs kickoff times out. We're correctly checking this but we're not cleaning up well afterwards:

# Acceptance criteria
* When the scan is invalid it is reported back to GDA nicely (Note that this is a warning for GDA it shouldn't stop the queue)
* This cleans up the detector and does not leave it in an armed state

**Comment by DominicOram** [comment]
Dirty fix on beamline, I think Bluseky should be clearing up on the `stage_decorator` but we're forcing it instead. Probably needs to all b a bit more explicit anyway. Also, could log better to GDA. https://ispyb.diamond.ac.uk/dc/visit/cm31105-4/dcg/8100125

**Comment by DominicOram** [comment]
@JimboMonkey my reading of db files is rusty. Can we be sure that `SCAN_INVALID` is in the correct state after we've got all the callbacks from `STEP_SIZE` etc.? I.e. do we need to wait for scan_invalid to be low or can we just wait on the callback and read it once? Similarly with `POS_COUNTER_WRITE` and `POS_COUNTER`, we're waiting for `POS_COUNTER` to read the correct value after we've written 0 to the `WRITE` PV but can we just wait on it's callback then check once?

**Comment by JimboMonkey** [comment]
@DominicOram - for `POS_COUNTER_WRITE` I think you could safely wait for the callback as this single record does a direct write to the PMAC (ie there is no processing chain).  `POS_COUNTER` is on a 0.1 second poll so if you did wait on it, it would be a short wait.

For parameter changes, there is a short processing chain before `SCAN_INVALID `is reprocessed (it is reprocessed for every parameter change).  So I think there would technically be a race condition between the callback of the parameter and `SCAN_INVALID `updating, but it must be pretty negligible.  

The other alternative is that the validity is checked on your side.  The checks within EPICS are only testing to see if the values fall within the soft limit values (which are accessible as PVs)
