### ISSUE TITLE
Migrate to dls python3-pip-skeleton

### ISSUE THREAD

**Issue by evalott100** [DiamondLightSource/python-artemis#258]
Artemis uses pipenv as an inheritance from what controls were doing during its creating. The environment should be migrated the dls pip python skeleton: https://diamondlightsource.github.io/python3-pip-skeleton.

**Comment by DominicOram** [comment]
@dperl-dls FYI

**Comment by dperl-dls** [comment]
Ok, so we would actually like to use the same virtual env in a container too, or are they separate solutions?

Relatedly, is running in a container an option in production or only for development?

**Comment by graeme-winter** [comment]
In long game running in container would be very desirable. Don't know situation right now

**Comment by DominicOram** [comment]
Running in a container in production likely contains it's own issues see https://github.com/DiamondLightSource/python-artemis/issues/260

**Comment by evalott100** [comment]
Now it seems the CI linting and tests are working okay, still a little messy. I've asked David to look into adding his Dockerfile to this, hopefully the job will work...

I'll clean up and remove all deprecated stuff from the python skeleton and pipenv after we're sure CI is up and running.

**Comment by evalott100** [comment]
The CI works, however the coverage is only 7%, despite the fact that the tests pass, locally with the same command it's 72%.

**Comment by evalott100** [comment]
We still need to implement docker.
