### ISSUE TITLE
Move arming the eiger out of stage

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#262]
As documented on the bluesky wiki `stage` is not expected to take a meaningful amount of time. Bluesky therefore waits on any stage being complete before continuing. Arming the detector takes ~6s and we currently do it in the `stage`, we should move it out of the `stage` so that we can do other things concurrently.

## Acceptance Criteria
* Staging the eiger takes little time
* Starting to arm the detector can be done in parrallel with other tasks
* The staging/arming are done as soon as possible in the plan

**Comment by bentom08** [comment]
Just to note here - if we move the detector arm outside the stage method, the rest of the Eiger stage will still need to be completed before we start arming. If we want to save time, at best we can start staging the Eiger immediately so we can begin arming as soon as possible as well.

**Comment by DominicOram** [comment]
Yes, I think we should do the following:
* Split the `stage` in the `eiger` into two:
   1. Setting up for the arm, e.g. check stale params etc. (everything that needs to be done before the arm)
   2. Doing the arm
* We should then do 1. concurrently as that takes more time compared to 2

**Comment by evalott100** [comment]
I wasn't sure if the seperation in the above commit is what we're looking for. The arm is the only thing in the `stage` function, everything before is contained in the new `pre_arm` function, which is ran in a new thread in the fast grid scan plan

**Comment by DominicOram** [comment]
I'm going to move this back into `To Do` as I think it a chat as a group and some further thought

**Comment by DominicOram** [comment]
Suggestion from @callumforrester `stage`/`unstage` should arm/disarm if not already in that state.

**Comment by DominicOram** [comment]
Odin currently assumes that frames are coming in very soon after arming. This could be a bad assumption.
