### ISSUE TITLE
Logging: Integrate with graylog

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#27]
Graylog is used for logging across DLS. It would be useful if the Artemis logs can also be sent here.

## Acceptance Criteria
* Artemis logs are sent to graylog
* The correct meta-data is sent with the logs e.g. beamline

**Comment by DominicOram** [comment]
Note that during testing on i03 we were accidentally logging into the data analysis stream. This was caused by us loading in the zocalo config. As part of this ticket ensure this doesn't happen.

**Comment by DominicOram** [comment]
Note, we should also ensure we're not slowed down by using graylog e.g. https://docs.python.org/3/howto/logging-cookbook.html#dealing-with-handlers-that-block use

**Comment by DominicOram** [comment]
To get a local graylog up and running:
```
podman pod create --name graylog-pod
podman run -d --net host --pod=graylog-pod --name=mongo mongo:4.2
podman run -d --net host --pod=graylog-pod -e "http.host=0.0.0.0" -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" --name=elasticsearch docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
podman run -d --net host --pod=graylog-pod -e GRAYLOG_HTTP_EXTERNAL_URI="http://localhost:9000/" -e GRAYLOG_MONGODB_URI="mongodb://localhost:27017/graylog" -e GRAYLOG_ELASTICSEARCH_HOSTS="http://localhost:9200/" --name=graylog graylog/graylog:4.0
```

**Comment by DominicOram** [comment]
As part of this investigate the issue where we are currently sending logs to graylog as zocalo. I think this is a bug in zocalo that when we import the config it sets up the default logger with this behaviour. @rjgildea may be able to help more

**Comment by abbiemery** [comment]
> Note that during testing on i03 we were accidentally logging into the data analysis stream. This was caused by us loading in the zocalo config. As part of this ticket ensure this doesn't happen.

https://github.com/DiamondLightSource/python-artemis/pull/203 Solved by Richard
