### ISSUE TITLE
Graylog logging twice

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#273]
Currently we are getting every message in graylog twice, this is annoying and takes up unneccesary disk space in graylog.

## Acceptance criteria
* Messgaes are only logged once per message in graylog

**Comment by DominicOram** [comment]
First step is to see if you can reproduce using a local graylog instance (setting this up is documented in the README)

**Comment by evalott100** [comment]
I remember this happening in my last project and it just kinda fixed itself. I tried running in complete isolation from the rest of the code in a new virtual env - just


```python
import logging
from datetime import datetime
from graypy import GELFTCPHandler

my_logger = logging.getLogger("test_logger")
my_logger.setLevel(logging.DEBUG)

handler = GELFTCPHandler("graylog2.diamond.ac.uk", 12218)
my_logger.addHandler(handler)

my_logger.debug(f"Hello Graylog - {datetime.now()}")
```

The problem persists with this test code. I will refactor the code to resemble a method I've used before which I know works.

**Comment by evalott100** [comment]
Solved by changing the port for logging to graylog.
