### ISSUE TITLE
Add omega into s03

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#274]
Currently s03 does not have an omega axis and so Artemis fails to run against it, we should add one in.

**Comment by dperl-dls** [comment]
turns out it does have one, but it's named `Omega` instead of `OMEGA` as expected

**Comment by DominicOram** [comment]
@dperl-dls tried to do this but S03 wasn't playing ball. I will investigate

**Comment by DominicOram** [comment]
Confirmed using the following test that it is now correct:
```
import pytest

from artemis.devices.I03Smargon import I03Smargon


@pytest.mark.s03
def test_when_smargon_created_against_s03_then_can_connect():
    smargon = I03Smargon("BL03S", name="smargon")

    smargon.omega.wait_for_connection()
```
However, with the new PVs added in https://github.com/DiamondLightSource/python-artemis/pull/371 doing `smargon.wait_for_connection()` will fail. I'll make a new issue for this.
