### ISSUE TITLE
Comment on ispyb when zocalo fails to find centre

### ISSUE THREAD

**Issue by evalott100** [DiamondLightSource/python-artemis#276]
In #251, the logic on the grid scan was changed so that when zocalo fails to find the centre, logs are made to GDA and graylog,  and an Exception is raised. This is contained in `src/artemis/fast_grid_scan_plan.py` in `run_gridscan`. We also need to send out a comment to ispyb.

**Comment by DominicOram** [comment]
We should think a bit more generally here, any exception should be put into the ispyb comment. We should make sure these exception are human readable

**Comment by DominicOram** [comment]
I believe https://github.com/DiamondLightSource/python-artemis/pull/295 fixes this

**Comment by dperl-dls** [comment]
There's a separate PR, #319 for this
