### ISSUE TITLE
Add OAV edge detection to Artemis

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#294]
To calculate the grid positions we need to get the edges of the pin from the OAV image. To do this we need to read/write to a number of PVs on the OAV.

## Acceptance Criteria
* We understand and document what is required to set/read to do edge detection
* We can put the OAV in this mode and get the edges out through ophyd

**Comment by evalott100** [comment]
I've encountered what could be an annoying blocker. Everything I need to interact with is a PV and can be set up with Ophyd - with the one exception of the backlight brightness which isn't handled by a PV. It's handled by a keyence controller, which seems to be "most likely some java object" (according to Neil).

We'll need to think about how to handle this, if we can give it a PV.

**Comment by evalott100** [comment]
Closing due to this work being completed in #318
