### ISSUE TITLE
Be able to switch zocalo environment

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#301]
For testing artemis/experimental plans off the beamline we should be able to use e.g. `devrmq` instead of `artemis`, to allow "processing" by a mock zocalo. But, `zc.activate_environment("zocalo")` is hardcoded throughout artemis, including in unit tests. 

**acceptance criteria:**
- zocalo env can be specified at runtime e.g. through parameters or --dev flag
- tests on zocalo interaction reflect this

**Comment by dperl-dls** [comment]
@DominicOram @evalott100 

how do you think this is best implemented? parameters or runtime arg / flag?

**Comment by DominicOram** [comment]
So what we currently have is:
* A command line arg for whether we log to real/fake graylog
* We use the beamline parameter to say whether we use the real/simulated beamline

I think, like you said, a parameter would be good. It should default to using the `zocalo` environment if not specified

**Comment by dperl-dls** [comment]
@DominicOram I think we should default to a dev environment if not specified, see #356
