### ISSUE TITLE
Document requirements for rotation scan

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#308]
Before we start on doing the rotation scan we should have a good idea of what is required to do it. This information should be gathered from chatting to the scientists and by examining the GDA code.

## Acceptance Criteria
* There is a document somewhere describing what is required for rotation scans, including:
     * Anything we need to between grid and rotation scans
     * Particularly noting any additional devices we need to communicate with
     * Any differences in the way we need to interact with ispyb/nexgen/zocalo
     * The logic of the scan itself

**Comment by DominicOram** [comment]
Note, I've changed wording to _rotation_ scan rather than _omega_ as we should probably think as we're doing it about making sure it could work in the generic case.

**Comment by DominicOram** [comment]
This will be a continuous scan and so we need to do similar to the grid scan in:
* Set up for nexus/ispyb
* Set up the eiger
* Set up zebra to do position compare on rotation axis
* Trigger a flyscan on the omega

**Comment by dperl-dls** [comment]
To be documented as github issues.

Functionality in the end will be to process a list of continuous rotation scans - so the same plan could do a single 360 rotation, 4 characterisation images at 90 degrees from eachother, or several collects on a multipin
