### ISSUE TITLE
Document and add unit tests to current i24 SSX code

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#309]
The current I24 SSX code lives at /dls_sw/i24/scripts/serial-collect/ we should understand it better before trying to reproduce it in Artemis.

## Acceptance Criteria
* There is documentation for what this code is doing and how it differs from Artemis
* Optionally there are some unit tests covering this code that we can use to confirm Artemis behaviour

**Comment by noemifrisina** [comment]
Bits and pieces of code being collected in [mx_bluesky12](https://github.com/DiamondLightSource/mx_bluesky/pull/12)

**Comment by dperl-dls** [comment]
closing because this is an mx_bluesky thing now
