### ISSUE TITLE
Investigate bluesky service

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#31]
The current infrastructure for starting/stopping scans from GDA (done in https://github.com/DiamondLightSource/python-artemis/pull/28) works OK but is not very extensible. The core team have already created https://gitlab.diamond.ac.uk/daq/d2acq/services/bluesky-service that performs a similar task. We should evaluate whether it could be used on Artemis.

## Acceptance Criteria
* There is a branch where the bluesky-service is integrated with Artemis
* There are some notes about the advantages/disadvantages of using it over the current model
* A decision is made about whether we use this service

**Comment by DominicOram** [comment]
Initial thoughts:

Advantages:
* We stress test bluesky-service (which is likely to be what is used on future bluesky projects)
* We will be forced to write some GDA code to communicate with the bluesky-service (again useful for future)

Disadvantages:
* The bluesky service contains more complexity than we (currently) need for Artemis

**Comment by DominicOram** [comment]
@callumforrester is working on a cut down version of the Bluesky service which will work better for us

**Comment by evalott100** [comment]
The gitlab repo above is an old prototype,  https://github.com/DiamondLightSource/blueapi/milestone/15, is the new repo for the bluesky service.

**Comment by DominicOram** [comment]
Clearing assignee from this as we're waiting on blueapi to be ready

**Comment by DominicOram** [comment]
@callumforrester has made a start on this but it needs a Hyperion dev to finish it off

**Comment by DominicOram** [comment]
I think we can call this investigation done with the conclusion that `blueapi` is now in a good enough state that we can start using it, thanks to @callumforrester. Subsequent issues to integrate properly in due course
