### ISSUE TITLE
Document Artemis for new Bluesky developers

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#310]
See https://jira.diamond.ac.uk/browse/MXGDA-3937

**Comment by DominicOram** [comment]
Documentation at https://github.com/DiamondLightSource/python-artemis/wiki/Getting-Started. @evalott100, @dperl-dls or @bentom08 can you review if there are any glaring mistakes?

**Comment by dperl-dls** [comment]
I don't see any glaring mistakes.

**Comment by DominicOram** [comment]
Thanks @dperl-dls, I'm going to call this done from the Artemis side
