### ISSUE TITLE
Formalise and document releases and deployments

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#314]
Now that Artemis is getting close to being in production we should improve and document:
* Release processes (including release notes)
* Deployment processes

These processes should aim to be as automated as possible

**Comment by DominicOram** [comment]
Suggest using something like https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/Release-Notes-v7.3.0.md as a template for release notes. Important features of this:
* Links to all issues
* List changes as patch/minor/major
* Highlight changes that we know may have large consequences

**Comment by rjgildea** [comment]
We’ve used [towncrier](https://towncrier.readthedocs.io/en/stable/) relatively successfully in [dials](https://github.com/dials/dials/tree/main/newsfragments) - it pushes you down the path of making release-note suitable descriptions of individual changesets which makes the process of compiling release notes significantly easier. We even have a [GitHub action](https://github.com/dials/dials/blob/main/.github/workflows/newsfragments.yml) that checks for newsfragments with PRs and automatically renames placeholder newsfragments.

**Comment by DominicOram** [comment]
Given our system tests are not yet automated we should add running them to the instructions for doing a release

**Comment by DominicOram** [comment]
Linked PR does some basic release notes, we can categorise them better in the future

**Comment by DominicOram** [comment]
As part of a deploy we will also need to set permissions so that scientists can edit the code
