### ISSUE TITLE
OAV Centring

### ISSUE THREAD

**Issue by evalott100** [DiamondLightSource/python-artemis#333]
GDA currently carries out OAV centring on the pin.

Acceptance Criteria:
* Rotation of the pin to find the biggest width
* Takes the centre at the biggest width, and the centre at the angle orthogonal to the biggest width, Combines them to make a 3D coordinate.
* Translates the 3D coordinates to smargon xyz motor coordinates, and moves there.

**Comment by evalott100** [comment]
Closing since acceptance criteria are met, will next write system tests.

**Comment by DominicOram** [comment]
I don't think we can call this done until https://github.com/DiamondLightSource/python-artemis/pull/394 is merged?
