### ISSUE TITLE
Replace Point3D with something which supports arithmetic

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#348]
Currently Point3D is a NamedTuple which is sort of fine, but we have to do stuff like:

`corrected_centre = Point3D(xray_centre.x - 0.5, xray_centre.y - 0.5, xray_centre.z - 0.5)`

instead of being able to just subtract (0.5, 0.5, 0.5).

If we ever need to do more arithmetic with vectors/coordinates then we should replace this with a more robust class, potentially a simple homemade one which can just add/subtract/multiply/divide, but ideally with one from a well-maintained module which supports distances, angles and whatnot, and might be a bit optimised.

**Comment by DominicOram** [comment]
Use `numpy` and get rid of names of `x, y, z`.

**Comment by dperl-dls** [comment]
Maybe this is a good issue for @olliesilvester , it's not extremely complicated, but it touches lots of areas of the code, what do you think @DominicOram ?

**Comment by DominicOram** [comment]
Yep, sounds good

**Comment by DominicOram** [comment]
@dperl-dls to re-review
