### ISSUE TITLE
Grid scans of the same size cause GDA do not wait for Artemis

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#35]
Currently if you do one grid scan with the same number of images after another you get the following behavior:
* The old number of images is still set on the FGS device from the previous scan
* GDA tells Artemis to start
* GDA starts polling the FGS for how many images it has done and sees that the old number is still there, assumes it has all finished
* Artemis sets the FGS to 0, by now it's too late and GDA has continued

**Comment by DominicOram** [comment]
Options to fix this include:
* Get GDA to wait for a 0 first
* Get Artemis to report it's progress and GDA to watch this rather than the PVs (maybe better?)

**Comment by dperl-dls** [comment]
is this still an issue? reopen if so
