### ISSUE TITLE
OAV: get gridscan grid from waveforms 

### ISSUE THREAD

**Issue by evalott100** [DiamondLightSource/python-artemis#373]
Artemis should be able to get the grid to do the 3D xray centre based on the OAV image.

## Acceptance Criteria
* The grid size etc. is determined from the OAV image (for 0 and 90)
* Snapshots with grids are taken through Artemis
* This data is passed on correctly to existing code, which performs the grids
* GDA is able to trigger this, as well as just the xray centre with provided parameters
* There are sufficient system/unit tests around this

**Comment by DominicOram** [comment]
Some initial work on this was done in https://github.com/DiamondLightSource/python-artemis/commit/0f70132c299f9f4fd8843d707b53cc041314c490. https://github.com/DiamondLightSource/python-artemis/issues/554 documents some of the issues found
