### ISSUE TITLE
S03: Put in all the PVs for the smargon

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#377]
Since https://github.com/DiamondLightSource/python-artemis/pull/371 there are now more PVs that we're using in the smargon, such that `smargon.wait_for_connection()` will fail against S03. We should add those PVs in.

## Acceptance Criteria
* The required PVs are added to S03
* There are system tests in Artemis to confirm this

**Comment by dperl-dls** [comment]
When this is done, TESTING_I03Smargon should be removed

**Comment by DominicOram** [comment]
Done [here](https://gitlab.diamond.ac.uk/controls/support/bl03s-builder/-/commit/86bb30817fd7cce6dc471343eab8a0c8ad7a37c7) apologies for push to master
