### ISSUE TITLE
Hardware changes required for rotation scans

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#378]
To do a rotation scan we will need to set up the hardware in a different way to doing the grid scan. Particularly it will require changes to:
* Configuring the Zebra
- [x] #524
* Configuring the Eiger
- [x] #525
* Combining these in one plan
- [x] #526

**Comment by dperl-dls** [comment]
What is this again?

**Comment by DominicOram** [comment]
https://github.com/DiamondLightSource/python-artemis/issues/355 is the first step for this in refactoring the zebra to more easily allow different modes of operation

**Comment by dperl-dls** [comment]
Closing after successful test run - implementation into plan in a separate issue
