### ISSUE TITLE
Fix  bugs from oav centring

### ISSUE THREAD

**Issue by evalott100** [DiamondLightSource/python-artemis#421]
When testing oav centring we encountered bugs:
* The oav centring would appear to be working, then the pin would suddenly veer off way too far (+y_pixels, or +x in the beamline coordinate system).

Testing criteria:
* Ensure these features work on next  test.

**Comment by DominicOram** [comment]
Now working as of https://github.com/DiamondLightSource/python-artemis/pull/456
