### ISSUE TITLE
Artemis does not have ability to read comments in ispyb

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#427]
When a grid scan fails Artemis tries to do the following:
* Write unsuccessful to the status in Ispyb
* Append a reason to the comment in Ispyb as to why it was unsuccessful

Currently the 2nd part is failing as to do the append we are trying to first read the current comment using the user specified in `ispyb-artemis-i03.cfg`. However, the user does not have read permissions.

## Acceptance Criteria
* Artemis has read permissions required to append to the comment
* Alternatively Artemis keeps the comment in memory and appends to it but I would rather not hold state that we don't need to

**Comment by DominicOram** [comment]
@KarlLevik how would you feel about us adding read permissions for the Artemis user?

**Comment by dperl-dls** [comment]
Instead of reading the comment we now have a procedure to append to it.
