### ISSUE TITLE
Check OAV zoom level without hard coding acceptable values

### ISSUE THREAD

**Issue by evalott100** [DiamondLightSource/python-artemis#452]
The OAV zoom level is an enum which has values
0 = "1.0x"
1 = "2.5x"
2 = "5.0x"
3 = "7.5"
4 = "10.0x"

Currently we check a zoom level (received from GDA in OAVCentring.json) is acceptable by checking if it is in a hard coded list
``` Python    
# Level is the arbitrary level  that corresponds to a zoom percentage.
    # When a zoom is fed in from GDA this is the level it is refering to.
    level: EpicsSignal = Component(EpicsSignal, "MP:SELECT")
    allowed_zooms = ["1.0x", "2.5x", "5.0x", "7.5x", "10.0x"]
```

We should instead get the list of acceptable zoom levels from the PV directly.

**Comment by DominicOram** [comment]
They should be available from fields on the PV, see https://epics.anl.gov/EpicsDocumentation/AppDevManuals/RecordRef/Recordref-25.html
