### ISSUE TITLE
S03 should automatically find a free port and tell Artemis

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#458]
Currently we have issues where S03s conflict with each other if there are multiple ones running. However, it is useful to each have one running so that if we're running automated tests against it they don't conflict. The current system to do this is to change the `EPICS_CA_SERVER_PORT` and `EPICS_CA_REPEATER_PORT` ports to be on unique ports. This also requires any clients (i.e. Artemis) to be updated to use these ports too.

## Acceptance Criteria
* Create a script in `s03_utils` that looks for S03 PVs on successive ports until it finds one no one is using
* Start s03 under this port
* Write the ports to a file location
* Add using these ports to the Artemis dev startup script

**Comment by dperl-dls** [comment]
I've added a script to find free ports and write the environment variables to `~/.bashrc_local`, this allows running the tests with pytest in the terminal as well as not needing to add to the startup script

https://gitlab.diamond.ac.uk/controls/python3/s03_utils/-/tree/artemis458_find_free_port

**Comment by dperl-dls** [comment]
- but it should also check there are no other S03 on that port elsewhere on the network
- and log the port so we know which is which

**Comment by DominicOram** [comment]
I think we should also avoid using the real ports at all. This means we're less likely to accidentally hit real PVs e.g. like https://github.com/DiamondLightSource/python-artemis/issues/516#issuecomment-1418121458
