### ISSUE TITLE
Handle zocalo returning multiple crystals

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#476]
In some samples there could be more than one crystal. In this case we're prototyping Zocalo returning a list of centres, with the strength of each one. The json returned from zocalo will look something like:
```
[
  {
    "centre_of_mass": [
      4.636612650133922,
      6.038044420033806,
      2.612136870930547
    ],
    "max_count": 156032.0,
    "max_voxel": [
      3,
      7,
      1
    ],
    "n_voxels": 65,
    "total_count": 6671044.0
  },
  {
    "centre_of_mass": [
      3.5,
      11.5,
      11.039976728723405
    ],
    "max_count": 103952.0,
    "max_voxel": [
      3,
      11,
      11
    ],
    "n_voxels": 2,
    "total_count": 192512.0
  }
]
```

## Acceptance Criteria
* Artemis chooses which crystal to go to based on the most `total_counts`
* System tests and fake_zocalo updated to reflect this

**Comment by DominicOram** [comment]
Testing on this will be happening 26/02/23

**Comment by rjgildea** [comment]
By way of example, for https://ispyb.diamond.ac.uk/dc/visit/cm31105-5/dcg/8424506 Zocalo will return a json string looking something like:
```
[
  {
    "bounding_box": [
      [
        0,
        1,
        1
      ],
      [
        5,
        9,
        10
      ]
    ],
    "centre_of_mass": [
      2.902023886839894,
      5.55764956832089,
      5.045271936984979
    ],
    "max_count": 156032.0,
    "max_voxel": [
      1,
      7,
      3
    ],
    "n_voxels": 161,
    "total_count": 12083976.0
  },
  {
    "bounding_box": [
      [
        8,
        10,
        2
      ],
      [
        12,
        12,
        4
      ]
    ],
    "centre_of_mass": [
      10.430489554536866,
      11.006540224656192,
      3.1069566434545264
    ],
    "max_count": 103952.0,
    "max_voxel": [
      11,
      11,
      3
    ],
    "n_voxels": 9,
    "total_count": 571540.0
  }
]
```
![Screenshot 2023-01-20 at 17 28 59](https://user-images.githubusercontent.com/2810624/213764882-10d4fb6f-ae6c-4a4d-8cae-828d5ece79bb.png)
The results will be sorted by `total_count` in descending order.

**Note: I have fixed the axis ordering in the values returned by Zocalo, such that they will now be `x,y,z` rather than `z,y,x`**

**Comment by DominicOram** [comment]
Testing went well and Artemis handles this fine. We should explicitly do the ordering of results though, rather than assuming Zocalo  will do so

**Comment by DominicOram** [comment]
As discussed, we should order the results again Artemis side. Whilst not 100% necessary we agreed that the deciding on order was Artemis' responsibility. This also makes it easier for us to do different ordering in the future too
