### ISSUE TITLE
Chose aperture based on crystal size

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#486]
Given richer data from zocalo we should be able to chose apertures e.g. a bigger crystal should use a bigger aperture. We just need the infrastructure for this, how to do the choosing should be discussed with scientists.

**Comment by dperl-dls** [comment]
from discussion with scientists:
- need the zocalo results in the ispyb comments
- need an easily configurable way to change the relationship btw bounding box & aperture choice, whether that just be very legible in the python or an external json/whatever
- with a preliminary default of 1 box -> 20um, 2 boxes -> 50um, 3+ boxes -> 100um
- i03 only care about the box size in x direction
- need to be able to turn on/off this adjustment

other notes:
- gda xraycentring.py resets the aperture with _clear_up() -> _clear_up_aperture(), this should check if artemis is setting it and not do it in that case

**Comment by DominicOram** [comment]
1. is covered by https://github.com/DiamondLightSource/python-artemis/issues/513

**Comment by DominicOram** [comment]
When moving the aperture we may have to be careful of collisions. See the `combined_aperture_scatterguard_scintillator.py` script in GDA
