### ISSUE TITLE
GDA restart artemis script reports artemis started when it is not started

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#497]

**Comment by dperl-dls** [comment]
because, for some reason, artemis was not installed

run script should probably check that artemis is actually running rather than just that the start command has been executed

**Comment by DominicOram** [comment]
The `curl --head -X GET --retry 5 --retry-connrefused --retry-delay 1 http://localhost:5005/fast_grid_scan/status >/dev/null 2>&1` line is failing 'cos the version of curl on the beamline is old.

Additionally, we should have some logs so we can diagnose why Artemis fails to start
