### ISSUE TITLE
fallback position achieved is not the same as starting position, even though numbers are the same

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#509]
loop centering starts off at :
![Screenshot from 2023-01-27 15-13-53](https://user-images.githubusercontent.com/115003895/215120505-431c1a56-a9e6-4dec-883c-045cae24de16.png)

but, after artemis grid scan gets no diffraction from zocalo we fallback to position:
![Screenshot from 2023-01-27 15-12-46](https://user-images.githubusercontent.com/115003895/215120711-a471289e-c82c-4a86-8284-a0055fe7d5cd.png)

see: https://ispyb.diamond.ac.uk/dc/visit/cm33866-1/dcg/8688395
end movement: https://graylog2.diamond.ac.uk/messages/logs_8156/f4b00052-9e54-11ed-bf19-1866dafadc6c
start movement: https://graylog2.diamond.ac.uk/messages/logs_8156/e7804ca0-9e54-11ed-bf19-1866dafadc6c
note that the numbers are the same but the position clearly is not

**Comment by dperl-dls** [comment]
because we are going to grid box 1 instead of the actual starting position

**Comment by DominicOram** [comment]
This may be because GDA is moving us to the start position before kicking off Artemis. The fallback position we use is the smargon location when Artemis is started, assuming it has been left at the optical centre, but if GDA has done the move to start first then the fallback will be grid start. We should remove this from GDA.

**Comment by dperl-dls** [comment]
That seems right, this happens at line 333 of artemis_grid_scan in GDA

**Comment by DominicOram** [comment]
GDA no longer starts us in the first position but maintains the optical centre, we need to test that this fixes the issue.
