### ISSUE TITLE
issues from testing 2.0.0

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#551]
- setup is called for every experiment type, leading to a NotImplemented error on main
- upper left and position interpreted as dict then converted to point3D - was incorrect - should fix and test for correct values
- check up on double conversion when those values go from external -> internal
- The positions of each crystal is specified to too many decimal places

**Comment by DominicOram** [comment]
Additionally `run_artemis` still claims artemis has started despite the issue in 1)
