### ISSUE TITLE
Tidy up OAV devices and grid plan

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#554]
Some OAV device namings are confusing, e.g.:

- [x] MJPG is called "snapshot"
- [x] inconsistent use of `input_plugin_pv` and `input_pv` (maybe areadetector plugins should be a class...)
- [x] chain plugins generically or at least in a consistent way
- [ ] structure of snapshot/snapshotwithgrid etc needs cleaning
- [x] `top_left_x_signal` etc. in snapshot device classes - add clarity that this refers to grid and remove redundant "signal"
- [x] take arguments for grid size, margin, # of boxes (eventually to come from json)
- [ ] deal with grid with no pin at zoom 0
- [ ] maybe average edge detection for stability, also maybe make sure rounding is correct so grid always extends to the edge of the sample
- [x] add backlight manipulation
- [x] `oav_centring_plan` should be in `experiment_plans` rather than `device_setup_plans`

also:
- [ ] look at bluesky visualisation options for live debugging

**Comment by DominicOram** [comment]
Spin out tickets to address the above that have not been addressed:
* https://github.com/DiamondLightSource/dodal/issues/50
* `deal with grid with no pin at zoom 0` - this seems like a way off, and will probably fall out of https://github.com/DiamondLightSource/python-artemis/issues/499
* ` maybe average edge detection for stability, also maybe make sure rounding is correct so grid always extends to the edge of the sample` - after tests on the beamline I think this was not much of an issue, we should get this on the beamline working and open a new issue if stability/accuracy become issues
* `look at bluesky visualisation options for live debugging` - can't remember what we exactly wanted to do with this, can pick it up if it's useful later
