### ISSUE TITLE
Test arming detector before grid detection

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#560]
If we can arm before grid detection we can produce some speed up. Currently we need to do grid detection for working out the number of images but after discussion with @GDYendell it should be possible to set the number of images to 0 and arm before/whilst working out grids.

## Acceptance Criteria
* Run with 0 frames and see if we still get good data
* We may need to be careful in the disarming to watch to make sure the number of written frames matches the expected number before disarming.

**Comment by GDYendell** [comment]
Ah - I may have misunderstood. The file writer accepts 0 to run forever, but the eiger does not. It also does not implement Continuous mode, despite being able to set that in the UI.

**Comment by DominicOram** [comment]
Hmm... What would happen if we just set an arbitrarily high number of frames then disarm part way through?

**Comment by GDYendell** [comment]
That could work, but you would get extra frames in the file in the delay between seeing it has the correct number and sending the stop. Is that a problem?

**Comment by DominicOram** [comment]
We're still using an external trigger, which will stop on it's own at the correct number of frames so I don't think there would be any additional?

**Comment by GDYendell** [comment]
Oh ideal then that will be fine.

**Comment by DominicOram** [comment]
Do you think we should be setting both Eiger and Odin to this arbitrary number or just the Eiger then Odin to 0? Probably best to go with whatever minimises potentially scary log messages

**Comment by GDYendell** [comment]
It is probably fine either way. Setting to 0 would be slightly neater because if you set the writer to an arbitrary number, then the that number will appear as the max size in the file and it won't be full. If you set zero it will just resize up to the correct size. I don't know if that makes any difference to you.

**Comment by DominicOram** [comment]
Attached commit tested on beamline and works, needs tidying
