### ISSUE TITLE
pixels per micron in parameters is actually microns per pixel

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#571]
when gda adds `pixels_per_micron` to the params it sends to artemis it is using a property which is `MicronsPerPixel`

**Comment by DominicOram** [comment]
Note that maths we're doing in places still seems to work so we might need to change that

**Comment by DominicOram** [comment]
We think think that we're sending the wrong value to ispyb so:
* Change the variable name throughout
* When pushing into ispyb use one over the value

**Comment by DominicOram** [comment]
Will also need to change the variable name that GDA sets
