### ISSUE TITLE
S03: update the container images for tickit-devices and gridscan

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#606]
We are still pulling the images from before the port environment variable changes

**Comment by DominicOram** [comment]
`tickit-devices` done in https://github.com/dls-controls/tickit-devices/pull/50

**Comment by DominicOram** [comment]
`gridscan` updated on s03_utils merge see https://console.cloud.google.com/gcr/images/diamond-pubreg/GLOBAL/controls/python3/s03_utils/devices/gridscan

**Comment by DominicOram** [comment]
I believe this is now all up to date. @dperl-dls, could you confirm?

**Comment by dperl-dls** [comment]
Yes, as far as I can tell
