### ISSUE TITLE
Zocalo issues on v4.0.0

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#630]
In testing v4.0.0 we found that zocalo returned no results for https://ispyb.diamond.ac.uk/dc/visit/cm33866-2/dcg/9256812

## Acceptance Criteria
* We work out what went wrong
* We have a good idea of how to diagnose these kinds of issues in the future

**Comment by rjgildea** [comment]
Partially addressed by https://github.com/DiamondLightSource/python-dlstbx/pull/210
