### ISSUE TITLE
full grid scan testing notes

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#658]
- aperture z check for safe move has no tolerance (??!!)
- running once works, twice does not
- pin tip centring dosn't happen at start of full grid scan (do we want it to?)
- sometimes num_images is negative (??!!) https://graylog2.diamond.ac.uk/messages/logs_8246/27ff3cc1-f308-11ed-9360-1866dafadc6c -> sometimes num_steps is negative - was default values for min and max grid size the wrong way round - we are hitting edge of image somtimes
- centre often wrong and snapshots often not displayed

**Comment by DominicOram** [comment]
1) covered in https://github.com/DiamondLightSource/dodal/issues/52

**Comment by DominicOram** [comment]
3. I think we don't want to for now, address in a later issue
