### ISSUE TITLE
Log what we are doing with external services

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#67]
We currently log a lot of the interactions we have with hardware as we get the logs for free from bluesky. However, we also need to log:
* Interactions with zocalo
* Interactions with ISPyB
* Interactions with nexgen
* Any exceptions/errors

**Comment by DominicOram** [comment]
We should also document where log files are stored etc

**Comment by dperl-dls** [comment]
I think this is part of #164 now, the document handler should and does log
