### ISSUE TITLE
Do a technical debt day

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#687]
We have a few issues recently where we focused on merging things quickly rather than 100% correct, with the shutdown we should spend a day doing tidying up jobs e.g. add unit tests, improve variable names etc.

## Acceptance Criteria
* We chose a day we're all free
* We book it out in the calendar
* We maybe invite the wider MX DAQ team to pair up?
* There are biscuits
* We work on anything that improves code quality/test coverage etc.

**Comment by DominicOram** [comment]
Could expand to `nexgen` and i24 SSX if we don't think there's enough in Hyperion

**Comment by DominicOram** [comment]
Discussed with @dperl-dls that a longer time, wehre we can focus on s03/system test automation would also be good

**Comment by DominicOram** [comment]
I have made a label (https://github.com/DiamondLightSource/python-artemis/issues?q=is%3Aopen+is%3Aissue+label%3A%22tech+debt+day%22) that we can put on issues. The idea is to put it on small things we can do in a day that will improve code quality, please add to these with any new/existing tickets. On the day feel free to bring in biscuits/cake then the aim is to pair up on these issues (ideally one experienced Hyperion dev and one with less experience on Hyperion) to get them done or mostly done by the end of the day.

**Comment by dperl-dls** [comment]
These issues were closed thanks to the help of snacks:
https://github.com/DiamondLightSource/python-artemis/pull/730
https://github.com/DiamondLightSource/python-artemis/issues/728
https://github.com/DiamondLightSource/python-artemis/issues/656
