### ISSUE TITLE
Pin too long exception handling

### ISSUE THREAD

**Issue by npat113** [DiamondLightSource/python-artemis#783]
Pins too long for the smargon travel range are triggering an exception that doesn't gracefully reset the detector from 4M mode. This results in the data collection failing and reinitialising (wasting several minutes).

2 issues:

Disarm and reset the detector settings gracefully in the event of an exception.

For pins out of range in non-artemis we cap the extent of the grid, not enter a fault. Artemis should behave like this until we can handle moving on to the next sample gracefully.

example:
https://ispyb.diamond.ac.uk/dc/visit/mx31353-61/dcg/9690888

**Comment by DominicOram** [comment]
Thanks @neil-i03, after discussion, I'm going to split this into two issues as I think they're independent:
* Ending up in a bad state after pin too long - https://github.com/DiamondLightSource/python-artemis/issues/790
* Handle pin too long more gracefully - https://github.com/DiamondLightSource/python-artemis/issues/791

As such I'm closing this one, if you think I've missed something feel free to re-open
