### ISSUE TITLE
Implement autoload (if required)

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#79]
After writing the nexus file GDA will write the filename to both:
* `${gda.beamline.var}/dials_image_viewer_file.txt`
* `${gda.beamline.var}/adxvAutoload.txt`

Presumably for analysis software to know where these files are.

## Acceptance Criteria
* Discuss with analysis people why these files exist - why can we not do everything through zocalo? (@graeme-winter, could you provide background on this?)
* Either implement this in Artemis, if required, or document why not required

**Comment by DominicOram** [comment]
@graeme-winter, @rjgildea and @neil-i03. We're not doing this in Artemis, is it something we need to do or is it a bit of legacy GDA we can drop?

**Comment by npat113** [comment]
Not required for UDC. It was for the in-person collection image viewing icons in the mx-launcher. Not even sure we use the adxv one any more as autoload runs via a Mark script. I suspect by the time artemis goes beyond I03 then it will have been replaced by something better.

**Comment by rjgildea** [comment]
I'm pretty sure neither of these files are used by data analysis.
