### ISSUE TITLE
Get smargon 'time to velocity' (eg BL03I-MO-SGON-01:OMEGA.ACCL) from epics

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#836]
Needed to calculate moves in the rotation scan. Really this should be added to ophyd epicsmotor, but we could add it ourselves separately for now. It's not clear whether the value is accurate or reliable - should confirm with a controls person. In any case, this is a minimum value, the cost in slightly exceeding it is very low.

**Comment by DominicOram** [comment]
@JimboMonkey do you think the `ACCEL` from `L03I-MO-SGON-01:OMEGA` is accurate and reliable enough for us to use it to work out triggering timings?

**Comment by DominicOram** [comment]
Ophyd issue for this is at https://github.com/bluesky/ophyd/issues/1141

**Comment by dperl-dls** [comment]
🤦‍♂️

**Comment by DominicOram** [comment]
The value currently in EPICS is 0.1s and the value we've hardcoded is 0.15s. Given these are quite different I suggest we test this before merging. If it is too fast then maybe we switch to `ACCL+some_extra_const` or `ACCL*some_extra_margin`. I think it's good to keep `ACCL` in there for readability and hopefully some level of portability.
