### ISSUE TITLE
Fix NoneType errors from dataclasses_json

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#88]
As a developer I would like it to be easier to work out why tests are failing. Currently there are a lot of errors of the form:
```
/home/runner/.local/share/virtualenvs/python-artemis-1IyxV7YB/lib/python3.7/site-packages/dataclasses_json/core.py:171: RuntimeWarning: `NoneType` object value of non-optional type beam_size_y detected when decoding IspybParams.
    warnings.warn(f"`NoneType` object {warning}.", RuntimeWarning)
```
These should be fixed

**Comment by evalott100** [comment]
The remaining errors are from the dependency event_model trying call `jsonschema.__version__` at some point, which is apparently deprecated.

**Comment by DominicOram** [comment]
Fixed in https://github.com/DiamondLightSource/python-artemis/pull/279
